// The account page's text (pt-BR and English).
import type { Locale } from "@/lib/i18n";

const errorsPt: Record<string, string> = {
  bad_token: "Código de configuração errado. Ele aparece no registro (log) do servidor na primeira vez que ele sobe.",
  setup_closed: "A conta deste servidor já existe. Entre com ela.",
  setup_unavailable: "Este servidor não tem um código de configuração (SETUP_TOKEN).",
  password_too_short: "A senha precisa ter pelo menos 12 caracteres.",
  password_too_long: "Senha longa demais.",
  bad_credentials: "Nome ou senha errados.",
  locked: "Muitas tentativas. Espere 15 minutos.",
  finish_setup: "A conta ainda não tem segundo fator: termine a configuração com o código de configuração.",
  rate_limited: "Muitas tentativas. Espere um minuto.",
  form: "Recarregue a página e digite o código de novo.",
  mfa_required: "Confirme o segundo fator de novo.",
  cancelled: "Cancelado.",
};
const errorsEn: Record<string, string> = {
  bad_token: "Wrong setup token. It is printed in the server's log the first time it starts.",
  setup_closed: "This server's account already exists. Sign in with it.",
  setup_unavailable: "This server has no setup token (SETUP_TOKEN).",
  password_too_short: "The password needs at least 12 characters.",
  password_too_long: "Password too long.",
  bad_credentials: "Wrong name or password.",
  locked: "Too many tries. Wait 15 minutes.",
  finish_setup: "The account has no second factor yet: finish the setup with the setup token.",
  rate_limited: "Too many tries. Wait a minute.",
  form: "Reload the page and type the code again.",
  mfa_required: "Confirm your second factor again.",
  cancelled: "Cancelled.",
};

const pt = {
  kicker: "Miblo · servidor próprio",
  title: "Sua conta neste servidor",
  titleFor: (name: string) => `Olá, ${name}`,
  lead: "Este servidor repassa as sessões do Miblo entre o seu computador e o seu celular, cifradas de ponta a ponta: ele nunca vê o conteúdo.",
  openApp: "Abrir o app do celular",
  close: "Fechar",
  working: "Um momento…",
  failed: "Não deu certo. Tente de novo.",
  or: "ou",
  setupTitle: "Criar a conta deste servidor",
  setupBody: "Uma conta só, a sua. Use o código de configuração que o servidor mostrou no registro (log) quando subiu. Depois você adiciona um segundo fator (passkey ou app autenticador), obrigatório.",
  setupUnavailable: "Este servidor ainda não foi configurado: defina SETUP_TOKEN (veja o README).",
  setupToken: "Código de configuração",
  username: "Nome",
  password: "Senha",
  passwordAgain: "Senha de novo",
  passwordHint: "Pelo menos 12 caracteres. A senha sozinha nunca basta: o segundo fator é obrigatório.",
  passwordsDiffer: "As senhas não são iguais.",
  setupSubmit: "Criar conta",
  signInTitle: "Entrar",
  signInPasskey: "Entrar com passkey",
  signIn: "Entrar com senha",
  passkeyFailed: "A passkey não foi aceita.",
  verifyTitle: "Confirme que é você",
  verifyBody: "Use seu segundo fator para continuar.",
  factorTitle: "Adicione um segundo fator",
  factorBody: "Sem ele nada funciona: crie uma passkey (recomendado) ou ative um app autenticador abaixo. Depois gere os códigos de recuperação.",
  factorDone: "Pronto, continuar",
  backToApp: "Voltar ao app do celular",
  linkTitle: "Vincular um computador",
  linkBody: "No computador, rode `miblo account link` e digite aqui o código que o terminal mostra.",
  linkWarning: "Só confirme um código que o SEU terminal está mostrando agora. Se alguém te mandou um código ou um link, não confirme.",
  codeLabel: "Código do terminal",
  continue: "Continuar",
  codeUnknown: "Código não encontrado ou expirado. Rode `miblo account link` de novo.",
  computer: "Computador",
  platform: "Sistema",
  asked: "Pedido",
  minutesAgo: (n: number) => (n <= 0 ? "agora" : `há ${n} min`),
  approve: "Vincular este computador",
  refuse: "Recusar",
  linked: (name: string) => `${name} vinculado.`,
  refused: "Pedido recusado.",
  deviceLimit: "Esta conta já tem o máximo de computadores. Desvincule um antes.",
  freshNeeded: "Para isso, confirme seu segundo fator de novo.",
  computersTitle: "Computadores vinculados",
  noComputers: "Nenhum ainda.",
  since: (d: string) => `desde ${d}`,
  seen: (d: string) => `visto ${d}`,
  unlink: "Desvincular",
  unlinkConfirm: (name: string) => `Desvincular ${name}? Ele para de usar este servidor e os celulares deixam de ver as sessões dele.`,
  unlinked: "Computador desvinculado.",
  phonesTitle: "Celulares",
  phonesBody: "Cada celular que entra nesta conta só recebe as chaves de um computador depois que você permite lá, digitando o código que o celular mostra.",
  noPhones: "Nenhum ainda. Abra o app do celular neste endereço e entre nesta conta.",
  withPasskey: "com passkey",
  withoutPasskey: "sem passkey (só acompanha)",
  computersCount: (n: number) => (n === 1 ? "1 computador" : `${n} computadores`),
  revoke: "Remover",
  revokePhoneConfirm: (name: string) => `Remover ${name}? Ele perde o acesso na hora.`,
  phoneRevoked: "Celular removido.",
  passwordTitle: "Trocar a senha",
  passwordChange: "Trocar senha",
  passwordChanged: "Senha trocada. As outras sessões foram encerradas.",
  signOut: "Sair",
  errors: errorsPt,
};

export type AccountStrings = typeof pt;

const en: AccountStrings = {
  kicker: "Miblo · self-hosted server",
  title: "Your account on this server",
  titleFor: (name: string) => `Hi, ${name}`,
  lead: "This server relays Miblo sessions between your computer and your phone, end-to-end encrypted: it never sees the content.",
  openApp: "Open the phone app",
  close: "Close",
  working: "One moment…",
  failed: "That did not work. Try again.",
  or: "or",
  setupTitle: "Create this server's account",
  setupBody: "One account, yours. Use the setup token the server printed in its log when it started. Then you add a second factor (a passkey or an authenticator app), which is mandatory.",
  setupUnavailable: "This server is not set up yet: set SETUP_TOKEN (see the README).",
  setupToken: "Setup token",
  username: "Name",
  password: "Password",
  passwordAgain: "Password again",
  passwordHint: "At least 12 characters. The password alone is never enough: the second factor is mandatory.",
  passwordsDiffer: "The passwords differ.",
  setupSubmit: "Create account",
  signInTitle: "Sign in",
  signInPasskey: "Sign in with a passkey",
  signIn: "Sign in with password",
  passkeyFailed: "The passkey was not accepted.",
  verifyTitle: "Confirm it is you",
  verifyBody: "Use your second factor to continue.",
  factorTitle: "Add a second factor",
  factorBody: "Nothing works without it: create a passkey (recommended) or turn on an authenticator app below. Then generate the recovery codes.",
  factorDone: "Done, continue",
  backToApp: "Back to the phone app",
  linkTitle: "Link a computer",
  linkBody: "On the computer, run `miblo account link` and type here the code the terminal shows.",
  linkWarning: "Only confirm a code YOUR terminal shows right now. If someone sent you a code or a link, do not confirm it.",
  codeLabel: "Code from the terminal",
  continue: "Continue",
  codeUnknown: "Code not found or expired. Run `miblo account link` again.",
  computer: "Computer",
  platform: "System",
  asked: "Asked",
  minutesAgo: (n: number) => (n <= 0 ? "just now" : `${n} min ago`),
  approve: "Link this computer",
  refuse: "Refuse",
  linked: (name: string) => `${name} linked.`,
  refused: "Request refused.",
  deviceLimit: "This account has the most computers it can have. Unlink one first.",
  freshNeeded: "For this, confirm your second factor again.",
  computersTitle: "Linked computers",
  noComputers: "None yet.",
  since: (d: string) => `since ${d}`,
  seen: (d: string) => `seen ${d}`,
  unlink: "Unlink",
  unlinkConfirm: (name: string) => `Unlink ${name}? It stops using this server and the phones no longer see its sessions.`,
  unlinked: "Computer unlinked.",
  phonesTitle: "Phones",
  phonesBody: "A phone that joins this account gets a computer's keys only after you allow it there, typing the code the phone shows.",
  noPhones: "None yet. Open the phone app at this address and sign in to this account.",
  withPasskey: "with a passkey",
  withoutPasskey: "no passkey (follows along only)",
  computersCount: (n: number) => (n === 1 ? "1 computer" : `${n} computers`),
  revoke: "Remove",
  revokePhoneConfirm: (name: string) => `Remove ${name}? It loses access at once.`,
  phoneRevoked: "Phone removed.",
  passwordTitle: "Change the password",
  passwordChange: "Change password",
  passwordChanged: "Password changed. Your other sessions were signed out.",
  signOut: "Sign out",
  errors: errorsEn,
};

export function accountStrings(lang: Locale): AccountStrings {
  return lang === "en" ? en : pt;
}
