// Copy of the phone app's PIN lock (AppLock.tsx), in every language the app has.
import type { Locale } from "@/lib/i18n";
import type { IdleChoice, PinProblem } from "./pin-lock";

const pt = {
  setupTitle: "Crie um PIN para o app",
  setupBody: "O PIN tranca o app do Miblo neste celular: as sessões, as aprovações, as respostas e os códigos só aparecem depois dele. Ele fica só neste aparelho e não vai para lugar nenhum.",
  newTitle: "Crie um PIN novo",
  newBody: "Você entrou de novo na conta. Crie um PIN novo para abrir o app.",
  pinLabel: "PIN (6 dígitos ou mais)",
  confirmLabel: "Repita o PIN",
  rules: "Só números, pelo menos 6. Nada de sequências (123456) ou repetições (111111, 121212).",
  save: "Salvar o PIN",
  saving: "Salvando…",
  mismatch: "Os dois PINs não são iguais.",
  problem: { digits: "Use só números.", short: "O PIN precisa ter pelo menos 6 dígitos.", long: "Use no máximo 12 dígitos.", trivial: "Esse PIN é fácil de adivinhar. Escolha outro." } as Record<PinProblem, string>,
  lockedTitle: "App trancado",
  lockedBody: "Digite o PIN para abrir o Miblo.",
  unlock: "Abrir",
  checking: "Conferindo…",
  wrong: (left: number) => (left === 1 ? "PIN errado. Mais 1 erro e o app é bloqueado neste celular." : `PIN errado. Restam ${left} tentativas antes do bloqueio.`),
  wait: (s: number) => `Muitos PINs errados. Tente de novo em ${s} s.`,
  waitShort: (s: number) => `Espere ${s} s`,
  blockedTitle: "Celular bloqueado",
  blocked: "Este celular foi bloqueado por PIN errado. Entre de novo na sua conta (digital/rosto ou app autenticador) para desbloquear.",
  blockedNote: "Por segurança, este celular saiu da sua conta e mandamos um aviso para o seu e-mail.",
  blockedPending: "Sem internet: este celular sai da conta assim que a conexão voltar.",
  signIn: "Entrar na conta",
  settingsTitle: "Trancar o app",
  settingsBody: "O app pede o PIN ao abrir e depois de um tempo sem uso. O PIN fica só neste celular.",
  idleLabel: "Trancar depois de",
  idle: { 1: "1 minuto sem uso", 5: "5 minutos sem uso", 15: "15 minutos sem uso", 60: "1 hora sem uso", leave: "Sempre que sair do app" } as Record<`${IdleChoice}`, string>,
  idleSaved: "Pronto, salvo.",
  change: "Trocar o PIN",
  changeCancel: "Cancelar",
  currentLabel: "PIN atual",
  newLabel: "PIN novo",
  changed: "PIN trocado.",
  lockNow: "Trancar agora",
  storage: "Não foi possível guardar o PIN neste navegador. Tente de novo; se continuar, saia do modo anônimo.",
  storageRead: "Não foi possível abrir o bloqueio do app neste navegador, então ele continua fechado. Recarregue a página; se continuar, saia do modo anônimo.",
};

export type LockStrings = typeof pt;

const en: LockStrings = {
  setupTitle: "Create a PIN for the app",
  setupBody: "The PIN locks the Miblo app on this phone: sessions, approvals, replies and codes only show after it. It stays on this device and is never sent anywhere.",
  newTitle: "Create a new PIN",
  newBody: "You signed in to your account again. Create a new PIN to open the app.",
  pinLabel: "PIN (6 digits or more)",
  confirmLabel: "Repeat the PIN",
  rules: "Numbers only, at least 6. No runs (123456) or repeats (111111, 121212).",
  save: "Save PIN",
  saving: "Saving…",
  mismatch: "The two PINs don't match.",
  problem: { digits: "Use numbers only.", short: "The PIN needs at least 6 digits.", long: "Use at most 12 digits.", trivial: "That PIN is easy to guess. Pick another one." },
  lockedTitle: "App locked",
  lockedBody: "Type your PIN to open Miblo.",
  unlock: "Unlock",
  checking: "Checking…",
  wrong: (left: number) => (left === 1 ? "Wrong PIN. One more and the app is blocked on this phone." : `Wrong PIN. ${left} tries left before the app is blocked.`),
  wait: (s: number) => `Too many wrong PINs. Try again in ${s} s.`,
  waitShort: (s: number) => `Wait ${s} s`,
  blockedTitle: "Phone blocked",
  blocked: "This phone was blocked after too many wrong PINs. Sign in to your account again (fingerprint/face or authenticator app) to unblock it.",
  blockedNote: "For your safety, this phone was signed out of your account and we sent a notice to your email.",
  blockedPending: "No internet: this phone signs out of the account as soon as it's back online.",
  signIn: "Sign in",
  settingsTitle: "App lock",
  settingsBody: "The app asks for the PIN when it opens and after a while unused. The PIN stays on this phone.",
  idleLabel: "Lock after",
  idle: { 1: "1 minute unused", 5: "5 minutes unused", 15: "15 minutes unused", 60: "1 hour unused", leave: "Whenever I leave the app" },
  idleSaved: "Saved.",
  change: "Change PIN",
  changeCancel: "Cancel",
  currentLabel: "Current PIN",
  newLabel: "New PIN",
  changed: "PIN changed.",
  lockNow: "Lock now",
  storage: "The PIN could not be saved in this browser. Try again; if it keeps failing, leave private browsing.",
  storageRead: "The app lock could not be read in this browser, so the app stays closed. Reload the page; if it keeps failing, leave private browsing.",
};

export function lockStrings(lang: Locale): LockStrings {
  return lang === "en" ? en : pt;
}
