// Copy of the phone app (/app, /en/app). Kept apart from the site dictionary: the app is its own
// installable shell. Plain words first: terminal commands only ever appear inside the
// "for the terminal" disclosures (`tech`), never as the main instruction.
import type { Locale } from "@/lib/i18n";

/** A wait said plainly: seconds up to 2 min, then minutes, then hours (the wait goes up to 1 h). */
function waitText(s: number): string {
  if (s <= 120) return `${s} s`;
  if (s < 3600) return `${Math.ceil(s / 60)} min`;
  return `${Math.ceil(s / 3600)} h`;
}

const pt = {
  lang: "pt" as "pt" | "en",
  apps: {
    title: "Apps",
    help: "Os apps são ligados e configurados no app Miblo do computador.",
    setup: (name: string) => `Configure o app ${name} no computador`,
    off: "Desligado",
    previewAlt: (name: string) => `${name}: o que ele mostra no Miblo`,
  },
  appName: "Miblo",
  tabs: { now: "Agora", miblo: "Meu Miblo", settings: "Ajustes" },
  tabsLabel: "Seções do app",
  computers: "Computadores",
  computerPicker: "Escolha o computador",
  addComputer: "Ligar outro computador",
  status: {
    connecting: "Conectando…",
    waiting: "Conectado. Esperando o computador mandar as sessões.",
    live: "Ao vivo",
    stale: (ago: string) => `Sem notícias do computador há ${ago}`,
    staleHint: "O computador pode estar desligado, dormindo ou sem internet.",
    offline: "Sem internet no celular. Tentando de novo…",
    retrying: "A conexão caiu. Tentando de novo…",
    refused: "Este computador não está mais ligado a este celular.",
    deleted: "O app do celular foi desligado no computador.",
    limit: "No plano grátis, só 1 celular fica conectado por vez. Feche o app no outro celular ou assine o Miblo+. Tentando de novo em 1 minuto…",
    pairAgain: "Ligar de novo",
  },
  needsYouCount: (n: number): string => (n === 1 ? "sessão precisa de você" : "sessões precisam de você"),
  allCalm: "Nenhuma sessão esperando por você",
  sessions: "Sessões",
  noSessions: "Nenhuma sessão aberta agora.",
  noSessionsHint: "Quando você abrir o Claude Code (ou outra IA) no computador, as sessões aparecem aqui.",
  more: (n: number) => (n === 1 ? "+1 sessão que não coube" : `+${n} sessões que não couberam`),
  state: { needs: "Precisa de você", working: "Trabalhando", done: "Terminou", idle: "Parada" } as Record<"needs" | "working" | "done" | "idle", string>,
  perm: "pede permissão",
  question: "fez uma pergunta",
  tools: { _wait_agents: "esperando agentes", _wait_tasks: "esperando tarefas", _compact: "compactando a conversa" } as Record<string, string>,
  limits: "Limites de uso",
  h5: "Janela de 5 horas",
  d7: "Semana",
  resets: (when: string) => `renova ${when}`,
  noLimits: "Os limites aparecem depois da próxima resposta do Claude Code no computador.",
  today: "Hoje",
  turns: (n: number) => (n === 1 ? "1 resposta" : `${n} respostas`),
  work: (d: string) => `${d} trabalhando`,
  cost: (v: string) => `${v} em uso`,
  updated: (t: string) => `Atualizado às ${t}`,
  miblo: {
    yours: "Seus Miblos",
    screen: {
      alert: "Precisa de você",
      work: "Trabalhando",
      idle: "De olho nas sessões",
      pet: "Modo bichinho",
      sleep: "Dormindo",
    } as Record<"alert" | "work" | "idle" | "pet" | "sleep", string>,
    online: "Online",
    offline: "Offline",
    offlineHint: "O computador não alcança este Miblo agora.",
    offlineHelp: "Confira se o Miblo está ligado na tomada e no mesmo Wi-Fi do computador.",
    myPet: "Com o seu pet do Miblo Studio",
    unavailable: "Não deu para desenhar o Miblo.",
    picture: (name: string, state: string) => `${name}, ${state}`,
    open: (name: string) => `Ver ${name}`,
    others: (n: number) => (n === 1 ? "e mais 1 Miblo" : `e mais ${n} Miblos`),
    none: "Nenhum Miblo ligado a este computador",
    liveAlt: "A tela do Miblo, ao vivo",
    liveOf: (name: string) => `Ao vivo, como no ${name}`,
    liveFactory: "Ao vivo, como num Miblo",
    app: (tool: string) => `App: ${tool}`,
    appHelp: "Um programa do computador colocou a própria tela. Ela entra na vez dela no Miblo, e os avisos do Miblo vêm sempre antes.",
    appBg: "fundo no Miblo",
    appBgHelp: "O fundo desta tela fica no Miblo. Aqui o app aparece sobre um fundo neutro.",
  },
  approvalsWaiting: (n: number) => (n === 1 ? "1 pedido esperando você" : `${n} pedidos esperando você`),
  see: "Ver",
  notify: {
    title: "Avisos",
    enable: "Ativar avisos",
    enabled: "Avisos ativados. O celular toca quando uma sessão precisar de você.",
    denied: "Os avisos estão bloqueados para o Miblo.",
    deniedHow: {
      ios: ["Abra os Ajustes do iPhone.", "Toque em Notificações e depois em Miblo.", "Ligue Permitir Notificações."],
      "android-app": ["Toque e segure o ícone do Miblo e escolha Informações do app.", "Toque em Notificações.", "Ligue as notificações e volte aqui."],
      android: ["Toque no ícone à esquerda do endereço, no topo do navegador.", "Toque em Permissões ou Notificações.", "Escolha Permitir e volte aqui."],
      other: ["Abra as configurações do navegador para este site.", "Permita as notificações.", "Volte aqui e recarregue a página."],
    } as Record<"ios" | "android-app" | "android" | "other", string[]>,
    unsupported: "Este navegador não recebe avisos. No Android, use o Chrome; no iPhone, instale o app na Tela de Início.",
    iosInstall: "No iPhone, os avisos só funcionam com o app na Tela de Início. Instale primeiro:",
    explain: "Um aviso simples, sem nada do seu computador: só que uma sessão precisa de você.",
    failed: "Não deu para ativar os avisos. Tente de novo.",
  },
  install: {
    title: "Instale o app",
    lead: "Fica na tela inicial, abre em tela cheia e recebe avisos.",
    button: "Instalar o Miblo",
    ios: ["Toque em Compartilhar, na barra do Safari.", "Role e escolha Adicionar à Tela de Início.", "Abra o Miblo pelo ícone novo."],
    android: ["Toque no menu ⋮ do navegador.", "Escolha Instalar app ou Adicionar à tela inicial.", "Abra o Miblo pelo ícone novo."],
    other: "No menu do navegador, escolha Instalar app ou Adicionar à tela inicial.",
    installed: "O app já está instalado neste celular.",
    dismiss: "Agora não",
  },
  pair: {
    title: "Ligue este celular ao seu computador",
    lead: "Veja suas sessões de IA de qualquer lugar. Leva um minuto.",
    steps: ["No computador, abra o app Miblo.", "Toque em Celular e depois em Mostrar o QR code.", "Escaneie o QR code com este celular."],
    scan: "Escanear o QR code",
    scanHint: "Aponte a câmera para o QR code na tela do computador.",
    noScanner: "Abra a câmera do celular e aponte para o QR code: ela abre o link certo.",
    camera: "Não deu para usar a câmera. Escaneie com o app de câmera do celular.",
    stop: "Fechar a câmera",
    cantScan: "Não consegue escanear?",
    pasteHelp: "Tem o link do QR code (o terminal mostra um, por exemplo)? Cole aqui.",
    paste: "Link do QR code",
    pasteButton: "Ligar",
    invalid: "Esse link não é um QR code do Miblo.",
    paired: (name: string) => `Pronto! Celular ligado ao ${name}.`,
    privacy: "Tudo chega criptografado de ponta a ponta: nem o servidor do Miblo consegue ler.",
    noApp: "Ainda não instalou o Miblo no computador?",
    noAppLink: "Veja como",
    otherPhone: "Já usou o Miblo em outro celular?",
    illustration: "O app Miblo no computador, na tela Celular, mostrando o QR code",
  },
  manageDevices: "Ver celulares e computadores da conta",
  remove: "Remover deste celular",
  removeConfirm: (name: string) => `Remover ${name} deste celular? Você pode ligar de novo depois pelo QR code.`,
  removed: (name: string) => `${name} removido.`,
  storageError: "Este navegador não deixa o app guardar a ligação (modo anônimo?).",
  close: "Fechar",
  computer: {
    details: "Detalhes",
    approvalsOn: "Aprovar e responder: ativado",
    approvalsOff: "Aprovar e responder: não ativado neste celular",
    check: "Código de conferência",
    checkHint: "O mesmo código aparece no computador, na lista de celulares.",
    current: "Mostrando agora",
    show: "Mostrar",
  },
  account: {
    menu: "Conta e ajuda",
    account: "Minha conta",
    signIn: "Entrar na conta",
    help: "Ajuda",
    site: "Site do Miblo",
    title: "Conta e ajuda",
  },
  tech: {
    label: "Para quem usa o terminal",
    on: "miblo phone on",
    link: "miblo account link",
    replies: "miblo plus replies on",
    channel: "claude --dangerously-load-development-channels server:miblo-phone",
    list: "miblo phone list",
  },
  plus: {
    name: "Miblo+",
    upsellTitle: "Responda e aprove pelo celular",
    upsellBody: "Com o Miblo+ você lê as conversas, responde e aprova pedidos das suas sessões de qualquer lugar.",
    upsellCta: "Conhecer o Miblo+",
    url: "/plus",
    active: "Miblo+ ativo neste computador",
    activeBody: "Conversas, respostas e aprovações pelo celular estão liberadas.",
    manage: "Ver minha assinatura",
    repair: "Para aprovar e responder por este celular, ligue-o pela sua conta Miblo.",
    open: "Abrir conversa",
    back: "Voltar",
    history: "Conversa",
    noHistory: "Nenhuma mensagem ainda. Elas aparecem aqui quando a IA responder.",
    loading: "Buscando as mensagens no computador…",
    historyBlocked: "As mensagens aparecem aqui quando este celular estiver registrado para aprovar e responder (veja abaixo).",
    historyOff: "O histórico está desligado no computador. Confirme as configurações no app Miblo (ou: miblo plus set history=on).",
    roles: { assistant: "IA", tool: "Ferramenta", user: "Você", phone: "Você (celular)" } as Record<"assistant" | "tool" | "user" | "phone", string>,
    replyLabel: "Responder (beta)",
    replyPlaceholder: "Escreva para a sessão…",
    send: "Enviar",
    replyOnlyClaude: "Por enquanto, dá para responder pelo celular só no Claude Code.",
    replyNeedsChannel: "Esta sessão não recebe respostas do celular. Responder pelo celular ainda é um teste (beta) e só funciona em sessões abertas de um jeito especial no computador.",
    replyEmpty: "Escreva alguma coisa antes de enviar.",
    replyTooLong: "Mensagem longa demais (até 4000 caracteres).",
    replySent: "Enviando ao computador…",
    replyHanded: "Enviada ao Claude Code, ainda não entregue à sessão.",
    replyStuck: "Ainda não entregue. Responder pelo celular é um teste (beta): a sessão precisa ter sido aberta de um jeito especial, senão o Claude Code descarta a mensagem.",
    replyDelivered: "Entregue à sessão.",
    replyRefused: "O computador recusou a mensagem.",
    replyOffline: "Sem conexão com o computador agora. Tente de novo.",
    approvals: "Pedidos de permissão",
    approvalTitle: (tool: string) => `Quer usar ${tool}`,
    kindTitle: {
      command: "Quer rodar um comando",
      edit: "Quer alterar um arquivo",
      read: "Quer ler arquivos",
      web: "Quer acessar a internet",
      other: "Quer usar uma ferramenta",
    } as Record<"command" | "edit" | "read" | "web" | "other", string>,
    approvalExpires: (s: number) => `expira em ${waitText(s)}`,
    approvalExpired: "Expirou. Responda no computador.",
    approvalPartial: "O pedido é grande demais para mostrar inteiro aqui. Pelo celular você só pode negar; para aprovar, use o computador.",
    approvalUnverified: "O que chegou não confere com o pedido. Só dá para negar.",
    approve: "Aprovar",
    deny: "Negar",
    confirmApprove: "Confirmar: aprovar exatamente isto",
    confirmDeny: "Confirmar: negar",
    cancel: "Cancelar",
    approvalSent: "Resposta enviada ao computador.",
    outcome: { allow: "Aprovado", deny: "Negado", timeout: "Sem resposta a tempo: voltou para o computador", answered: "Respondido no computador" } as Record<"allow" | "deny" | "timeout" | "answered", string>,
    untrusted: "Texto vindo da IA: confira antes de agir.",
    descriptionByAi: "Descrição escrita pela IA (pode não corresponder ao comando)",
    command: "Comando que vai rodar",
    file: "Arquivo",
    diff: "Alterações (− sai, + entra)",
    other: "Outros campos",
    counts: (lines: number, chars: number) => `${lines} ${lines === 1 ? "linha" : "linhas"} · ${chars} caracteres`,
    multiline: "Comando com várias linhas: leia todas antes de aprovar.",
    long: "Comando longo: leia até o fim antes de aprovar.",
    hidden: "Contém caracteres invisíveis ou de controle, ou acentos empilhados (mostrados como ⟨U+…⟩ ou ⟨ESC⟩). Por segurança, pelo celular só dá para negar.",
    nonAscii: "Contém caracteres fora do ASCII, que podem imitar letras comuns. Confira com atenção.",
    readToEnd: "Role até o fim do pedido para liberar o Aprovar.",
    passkeyNeeded: "Aprovar pede o Face ID, a digital ou o PIN deste celular.",
    passkeyCancelled: "Aprovação cancelada: o Face ID, a digital ou o PIN não foi confirmado.",
    replyPasskey: "Enviar pede o Face ID, a digital ou o PIN deste celular.",
    replyCancelled: "Mensagem não enviada: o Face ID, a digital ou o PIN não foi confirmado.",
    replyNoToken: "O computador ainda não liberou a resposta para esta conversa. Volte e abra a conversa de novo.",
    rekeyed: "O computador trocou a chave desta ligação (um celular foi removido). Este celular já recebeu a nova.",
    noPasskeys: "Este celular não tem Face ID, digital nem PIN disponível para o navegador. Aprovar e responder ficam indisponíveis; você continua vendo as sessões.",
    notEnrolled: "Este computador ainda não aceitou este celular. Confira se ele está ligado à mesma conta Miblo (no app Miblo do computador: Entrar com sua conta Miblo).",
    revoked: "Este celular foi removido no computador ou na sua conta. Para voltar, ligue este celular de novo pela sua conta.",
    enrollTitle: "Aprove e responda por este celular",
    enrollBody: "Toque abaixo e confirme com o Face ID, a digital ou o PIN do celular. Cada aprovação vai pedir isso de novo, e o computador confere.",
    enrollButton: "Ativar aprovações",
    enrolling: "Registrando no computador…",
    enrollDone: (fp: string) => `Pronto! Este celular já pode aprovar e responder. Código de conferência: ${fp}.`,
    enrollDoneTitle: "Pronto! Este celular já pode aprovar e responder.",
    checkCode: (fp: string) => `Código de conferência: ${fp} (o computador mostra o mesmo).`,
    enrollFailed: "O computador não aceitou. O QR code vale 10 minutos e para um celular só: gere outro no app Miblo do computador (Celular, Liberar aprovações num celular) e escaneie de novo.",
    enrollCancelled: "Não ativado: o Face ID, a digital ou o PIN não foi confirmado. Tente de novo enquanto o QR code vale (10 minutos).",
    enrollExpired: "O QR code já expirou. Para ativar, gere outro no app Miblo do computador (Celular, Liberar aprovações num celular) e escaneie de novo.",
    repliesOff: "Responder pelo celular está desligado neste computador.",
    ok: "Ok",
  },
  join: {
    title: "Entre na sua conta Miblo",
    lead: "O celular se liga pela sua conta Miblo: entre aqui e no computador com a mesma conta. Sem QR code.",
    legacy: "Entre na sua conta Miblo para continuar. As ligações antigas por QR code deixaram de valer.",
    signIn: "Entrar na conta",
    mfaSetup: "Para ligar um celular, sua conta precisa de uma segunda etapa (Face ID, digital ou app autenticador).",
    mfaSetupLink: "Ativar a segunda etapa",
    confirmTitle: "Confirme que é você",
    joinTitle: "Ligar este celular à sua conta",
    joinBody: (email: string) => `Este celular vai entrar na conta ${email}. Cada computador ligado a ela mostra este celular e só o aceita depois que você tocar em Permitir lá.`,
    joinPasskey: "Vamos criar uma passkey deste celular (Face ID, digital ou PIN): ela confirma cada aprovação, resposta e tarefa.",
    joinNoPasskey: "Este navegador não tem passkey: o celular vai só acompanhar (sem aprovar, responder ou rodar tarefas).",
    joinButton: "Ligar este celular",
    joining: "Ligando…",
    limit: "Sua conta já tem 5 celulares. Remova um em Minha conta, Dispositivos.",
    failed: "Não deu para ligar agora. Tente de novo.",
    cancelled: "Cancelado: o Face ID, a digital ou o PIN não foi confirmado.",
    waitingTitle: "Esperando seu computador",
    waitingBody: "No computador, abra o app Miblo e toque em Entrar com sua conta Miblo. Depois, toque em Permitir quando ele mostrar este celular.",
    waitingTech: ["miblo account link", "miblo phone on"],
    allowTitle: "Digite o código do computador",
    allowBody: "Aguardando confirmação no computador: abra o app Miblo, toque em Permitir e digite o código abaixo.",
    allowOn: (pc: string, min: number) => `${pc} · expira em ${min} min`,
    allowTech: ["miblo phone pending"],
    expiredOn: (pc: string) => `O pedido expirou em ${pc} antes de ser confirmado.`,
    askAgain: "Pedir de novo",
    askedAgain: "Pedido enviado: confirme no computador.",
    deniedOn: (pc: string) => `${pc} recusou este celular. Se foi engano, remova este celular em Minha conta e ligue de novo.`,
    checkNow: "Verificar agora",
    detail: {
      bad_key: (pc: string) => `Detalhes: ${pc} enviou o acesso, mas ele não abre com a chave deste celular (foi feito para outra tentativa). No computador, em Celular, revogue este celular e conecte de novo.`,
      bad_sig: (pc: string) => `Detalhes: o acesso enviado por ${pc} não está assinado por ele. Toque em Verificar agora; se continuar, revogue este celular no computador e conecte de novo.`,
      not_pinned: (pc: string) => `Detalhes: o acesso de ${pc} abre, mas este celular não guardou a confirmação do código digitado (outra tentativa, ou a sessão foi refeita). No computador, em Celular, revogue este celular e conecte de novo.`,
      type_code: (pc: string) => `Detalhes: ${pc} está mostrando o código. Digite acima.`,
      code_sent: (pc: string) => `Detalhes: código enviado; ${pc} está conferindo.`,
      held: (pc: string) => `Detalhes: ${pc} aceitou o código e espera a confirmação num celular que ele já tem. Se nenhum responder, revogue-o no computador: este celular entra só com o código.`,
      allow: (pc: string) => `Detalhes: ${pc} viu este celular e ainda não mostrou o código. No computador, abra Celular.`,
      no_answer: "Detalhes: nenhum computador respondeu ainda. Confira se o Miblo está ligado no computador (app Miblo, aba Celular, ou `miblo phone status`).",
    },
    joined: (name: string) => `Pronto! ${name} aceitou este celular.`,
    signedInAs: (email: string) => `Conta: ${email}`,
  },
  // v7: the computer shows the code; this phone types it (a new computer, a widening change).
  code: {
    title: (pc: string) => `Novo computador: ${pc}`,
    help: (pc: string) => `Digite o código de 6 dígitos que aparece em ${pc} (no app Miblo ou no terminal). Só digite se você estiver vendo esse computador agora.`,
    label: "Código do computador",
    submit: "Confirmar com a passkey",
    submitNoPasskey: "Confirmar",
    sending: "Confirmando…",
    sent: "Enviado: o computador confere o código.",
    wrong: (left: number) => `Código errado. ${left === 1 ? "Resta 1 tentativa" : `Restam ${left} tentativas`}.`,
    invalid: "Digite os 6 dígitos que o computador mostra.",
    cancelled: "Cancelado: a passkey não foi confirmada.",
    failed: "Não deu para enviar agora. Tente de novo.",
    gone: "Esse pedido mudou no computador: veja o código de novo.",
    held: (pc: string) => `Código certo. Agora confirme num celular que você já usa com ${pc}: ele vai pedir o código que o computador mostra.`,
    reuseTitle: "Você já tem uma chave de acesso do Miblo neste celular. Usar a mesma?",
    reuseYes: "Usar a que já tenho (recomendado)",
    reuseNo: "Criar outra",
    repairing: "Pedindo ao computador…",
    repairFailed: "Não deu para pedir de novo. Tente de novo.",
    retry: "Tentar de novo",
  },
  // v7: a change asked on the computer, confirmed here with the code it shows.
  confirm: {
    title: (pc: string) => `${pc} quer ligar:`,
    admitTitle: (pc: string) => `${pc}: novo celular quer acessar`,
    admitBody: (name: string, about: string) => `${name}${about ? ` (${about})` : ""}. Só permita se for seu.`,
    on: { approvals: "aprovações pelo celular", replies: "respostas pelo celular", history: "o histórico no celular", permissive: "respostas também em sessões que não pedem permissão", tasks: "novas tarefas pelo celular" } as Record<string, string>,
    timeout: (s: number) => `esperar o celular por ${waitText(s)} numa aprovação`,
    taskMax: (m: number) => `tarefas de até ${m} min`,
    folder: (path: string) => `tarefas na pasta ${path}`,
    help: "Digite o código de 6 dígitos que o computador mostra agora e confirme com a passkey.",
    expires: (s: number) => `Expira em ${s} s`,
    approve: "Aprovar pelo celular",
    deny: "Recusar",
    done: { applied: "Ligado no computador.", cancelled: "Cancelado.", expired: "Expirou.", wrong_code: "Código errado 3 vezes: cancelado.", failed: "O computador não conseguiu aplicar." } as Record<string, string>,
    phoneOnly: "Confirme pelo celular: este pedido só pode ser aprovado num celular.",
  },
  // Protocol v6 "Verifying a new phone" (security audit 1.21.0).
  trust: {
    codeTitle: (pc: string) => `Código para ${pc}`,
    codeHelp: "Este computador tem um Miblo anterior à 1.23: nele, toque em Permitir no app Miblo e digite este código (ou rode miblo phone approve com --code). Nunca o digite em outro lugar.",
    fp: (fp: string) => `Chave do computador: ${fp}`,
    preparing: "Preparando o código…",
    mismatch: "Um computador recebeu outra chave para este celular: o código não vai bater. Não permita; remova este celular em Minha conta e ligue de novo.",
    newTitle: (pc: string) => `Novo computador: ${pc}`,
    newBody: (code: string) => `Ele diz que você permitiu este celular com o código ${code}. Foi você, no seu computador?`,
    confirm: "Sim, fui eu",
    reject: "Não reconheço",
    rejected: "Recusado: este computador não recebe nada deste celular.",
    confirmed: (pc: string) => `${pc} confirmado.`,
    tooMany: "Muitas tentativas de parear: alguém pode estar tentando entrar. Nenhum código novo é mostrado por uma hora. Se não foi você, troque a senha e a segunda etapa da sua conta.",
  },
  chat: {
    jump: "Ir para o fim",
    jumpNew: (n: number) => (n === 1 ? "1 nova mensagem" : `${n} novas mensagens`),
    working: "Trabalhando…",
    copy: "Copiar",
    copied: "Copiado",
    more: "Ver tudo",
    less: "Mostrar menos",
    image: (alt: string) => (alt ? `[imagem: ${alt}]` : "[imagem]"),
    openLink: (url: string) => `Abrir este endereço?\n\n${url}`,
    today: "Hoje",
    yesterday: "Ontem",
    edited: (path: string) => `Editou ${path}`,
    wrote: (path: string) => `Criou ${path}`,
    ran: (cmd: string) => `Rodou: ${cmd}`,
    read: (path: string) => `Leu ${path}`,
    readN: (n: number) => `Leu ${n} arquivos`,
    searched: (q: string) => `Buscou: ${q}`,
    searchedN: (n: number) => `Fez ${n} buscas`,
    web: (q: string) => `Na web: ${q}`,
    agent: (q: string) => `Agente: ${q}`,
    todo: "Atualizou a lista de tarefas",
    used: (name: string) => `Usou ${name}`,
    usedN: (n: number) => `Usou ${n} ferramentas`,
    failed: "deu erro",
    output: "Saída",
    changes: "Alterações",
    disabledHow: "Como ligar",
    noReply: "Responder daqui não está disponível nesta sessão.",
    offPlaceholder: "Respostas desligadas aqui",
    replyOff: "Para responder daqui, ligue as respostas no computador.",
    replyChannel: "Para responder daqui, abra a sessão no computador com o canal do Miblo (beta).",
    replyOther: "Responder daqui funciona só no Claude Code. Para outras IAs, use Nova tarefa.",
    replyTask: "Tarefa do celular: para mandar mais, crie uma nova tarefa.",
    noPasskey: "Este celular não tem passkey: dá para acompanhar, não para responder.",
    notLinked: "Este celular ainda não foi aceito por este computador.",
    revoked: "Este celular foi removido neste computador.",
    offline: "Sem conexão com o computador agora.",
  },
  task: {
    newTask: "Nova tarefa",
    title: "Nova tarefa no computador",
    lead: "Peça a uma IA para trabalhar no computador, numa pasta que você liberou lá. Você acompanha tudo aqui.",
    tool: "IA",
    folder: "Pasta",
    prompt: "O que fazer",
    placeholder: "Ex.: rode os testes e corrija o que falhar",
    willRun: (tool: string, path: string) => `Vai rodar ${tool} em ${path}`,
    limit: (min: number) => `Para sozinha depois de ${min} min. Pedidos de permissão chegam aqui em Aprovações.`,
    send: "Enviar tarefa",
    passkey: "Enviar pede o Face ID, a digital ou o PIN deste celular.",
    off: "Tarefas pelo celular estão desligadas neste computador.",
    offHow: "No computador, escolha uma pasta e ligue as tarefas (pede o código do seu Miblo):",
    offTech: ["miblo plus tasks folder add <pasta>", "miblo plus tasks on"],
    noTools: "Nenhuma IA compatível encontrada no computador (Claude Code, Codex, Gemini CLI ou Copilot).",
    noFolders: "Nenhuma pasta liberada no computador ainda.",
    loading: "Perguntando ao computador o que dá para rodar…",
    sending: "Enviando…",
    started: "Tarefa iniciada no computador.",
    refused: (why: string) => `O computador recusou a tarefa (${why}).`,
    cancelled: "Não enviada: o Face ID, a digital ou o PIN não foi confirmado.",
    offline: "Sem conexão com o computador agora. Tente de novo.",
    empty: "Escreva o que a IA deve fazer.",
    tooLong: "Texto longo demais (até 4000 caracteres).",
    noToken: "O computador ainda não liberou tarefas para este celular. Feche e abra de novo.",
    stop: "Parar",
    stopConfirm: "Parar esta tarefa agora?",
    stopping: "Parando…",
    recent: "Tarefas recentes",
    states: { running: "Rodando", done: "Concluída", failed: "Falhou", stopped: "Parada" } as Record<"running" | "done" | "failed" | "stopped", string>,
    reasons: {
      busy: "já há uma tarefa rodando",
      rate_limited: "limite de tarefas por hora",
      off: "tarefas desligadas",
      unknown_folder: "pasta não liberada",
      folder_changed: "a pasta mudou no computador",
      unknown_tool: "IA não encontrada",
      passkey_none: "este celular não tem passkey",
      time_limit: "tempo esgotado",
      output_limit: "saída grande demais",
      phone: "parada pelo celular",
      computer: "parada no computador",
    } as Record<string, string>,
    needsPlus: "Nova tarefa faz parte do Miblo+.",
  },
  vault: {
    title: "Guardar na sua conta",
    lead: "Guarde na sua conta Miblo os computadores ligados a este celular. Num celular novo, é só entrar e recuperar. Fica criptografado: nem o Miblo consegue ler.",
    restoreLead: "Entre na sua conta para recuperar os computadores que você guardou.",
    nothingKept: "Nenhum computador guardado na sua conta ainda. Ligue este celular pelo QR code; depois, em Ajustes, você pode guardar.",
    signIn: "Entrar na conta",
    setup: "Para guardar, sua conta precisa entrar com Face ID ou digital (uma chave de acesso).",
    setupLink: "Ativar na minha conta",
    create: "Guardar na minha conta",
    open: "Ver computadores guardados",
    working: "Confirmando…",
    noPrf: "Este celular ou navegador não consegue abrir o que está guardado. Os computadores continuam ligados neste celular.",
    noPasskey: "Para abrir, use o Face ID ou a digital da conta (o código do app autenticador não serve aqui).",
    cancelled: "O Face ID, a digital ou o PIN não foi confirmado.",
    failed: "Não deu para abrir. Tente de novo.",
    otherKey: "Esta chave de acesso ainda não abre o que está guardado. Abra com a que guardou e libere esta depois.",
    empty: "Nada guardado ainda. Os próximos computadores ligados a este celular entram aqui.",
    here: "neste celular",
    restore: "Usar neste celular",
    forget: "Tirar da conta",
    save: "Guardar",
    seen: (when: string) => `visto ${when}`,
    neverSeen: "ainda não visto",
    notInVault: (n: number) => (n === 1 ? "1 computador deste celular não está guardado: para guardar, escaneie o QR code dele de novo." : `${n} computadores deste celular não estão guardados: para guardar, escaneie o QR code deles de novo.`),
    restored: "Recuperado para ver as sessões. Para aprovar e responder, registre este celular de novo no app Miblo do computador (Celular, Liberar aprovações num celular).",
    addKey: "Liberar outra chave de acesso",
    unlocked: "Pronto: estes são os computadores guardados na sua conta.",
    saveFailed: "Não deu para guardar: a mudança não foi salva. Tente de novo.",
    rekeyed: "Uma chave de acesso saiu da sua conta: o que está guardado ganhou uma chave nova, que só esta abre. Libere as outras de novo.",
    rollback: "O que chegou é mais antigo do que este celular já viu. Por segurança, não foi aberto.",
  },
};

export type PhoneStrings = typeof pt;

const en: PhoneStrings = {
  lang: "en",
  apps: {
    title: "Apps",
    help: "Apps are turned on and set up in the Miblo app on the computer.",
    setup: (name: string) => `Set up the ${name} app on the computer`,
    off: "Off",
    previewAlt: (name: string) => `${name}: what it shows on the Miblo`,
  },
  appName: "Miblo",
  tabs: { now: "Now", miblo: "My Miblo", settings: "Settings" },
  tabsLabel: "App sections",
  computers: "Computers",
  computerPicker: "Choose the computer",
  addComputer: "Connect another computer",
  status: {
    connecting: "Connecting…",
    waiting: "Connected. Waiting for the computer to send the sessions.",
    live: "Live",
    stale: (ago: string) => `No word from the computer for ${ago}`,
    staleHint: "The computer may be off, asleep or offline.",
    offline: "The phone has no internet. Trying again…",
    retrying: "The connection dropped. Trying again…",
    refused: "This computer is no longer connected to this phone.",
    deleted: "The phone app was turned off on the computer.",
    limit: "The free plan keeps 1 phone connected at a time. Close the app on the other phone or get Miblo+. Trying again in a minute…",
    pairAgain: "Connect again",
  },
  needsYouCount: (n: number) => (n === 1 ? "session needs you" : "sessions need you"),
  allCalm: "No session is waiting for you",
  sessions: "Sessions",
  noSessions: "No sessions open right now.",
  noSessionsHint: "When you open Claude Code (or another AI tool) on the computer, its sessions show up here.",
  more: (n: number) => (n === 1 ? "+1 session that didn't fit" : `+${n} sessions that didn't fit`),
  state: { needs: "Needs you", working: "Working", done: "Done", idle: "Idle" },
  perm: "asks for permission",
  question: "asked a question",
  tools: { _wait_agents: "waiting for agents", _wait_tasks: "waiting for tasks", _compact: "compacting the conversation" },
  limits: "Usage limits",
  h5: "5-hour window",
  d7: "Week",
  resets: (when: string) => `resets ${when}`,
  noLimits: "The limits show up after Claude Code's next answer on the computer.",
  today: "Today",
  turns: (n: number) => (n === 1 ? "1 reply" : `${n} replies`),
  work: (d: string) => `${d} working`,
  cost: (v: string) => `${v} of usage`,
  updated: (t: string) => `Updated at ${t}`,
  miblo: {
    yours: "Your Miblos",
    screen: { alert: "Needs you", work: "Working", idle: "Watching your sessions", pet: "Pet mode", sleep: "Asleep" },
    online: "Online",
    offline: "Offline",
    offlineHint: "The computer can't reach this Miblo right now.",
    offlineHelp: "Check that the Miblo is plugged in and on the same Wi-Fi as the computer.",
    myPet: "Running your Miblo Studio pet",
    unavailable: "Couldn't draw the Miblo.",
    picture: (name: string, state: string) => `${name}, ${state}`,
    open: (name: string) => `See ${name}`,
    others: (n: number) => (n === 1 ? "and 1 more Miblo" : `and ${n} more Miblos`),
    none: "No Miblo connected to this computer",
    liveAlt: "The Miblo screen, live",
    liveOf: (name: string) => `Live, as on ${name}`,
    liveFactory: "Live, as on a Miblo",
    app: (tool: string) => `App: ${tool}`,
    appHelp: "A program on the computer set its own screen. It takes its turn on the Miblo, and Miblo's own alerts always come first.",
    appBg: "background on the Miblo",
    appBgHelp: "This screen's background lives on the Miblo. Here the app shows over a plain one.",
  },
  approvalsWaiting: (n: number) => (n === 1 ? "1 request waiting for you" : `${n} requests waiting for you`),
  see: "See",
  notify: {
    title: "Alerts",
    enable: "Turn on alerts",
    enabled: "Alerts are on. Your phone buzzes when a session needs you.",
    denied: "Alerts are blocked for Miblo.",
    deniedHow: {
      ios: ["Open the iPhone Settings.", "Tap Notifications, then Miblo.", "Turn on Allow Notifications."],
      "android-app": ["Touch and hold the Miblo icon and choose App info.", "Tap Notifications.", "Turn notifications on and come back."],
      android: ["Tap the icon left of the address, at the top of the browser.", "Tap Permissions or Notifications.", "Choose Allow and come back."],
      other: ["Open the browser's settings for this site.", "Allow notifications.", "Come back and reload the page."],
    },
    unsupported: "This browser can't receive alerts. On Android, use Chrome; on iPhone, install the app on the Home Screen.",
    iosInstall: "On iPhone, alerts only work with the app on the Home Screen. Install it first:",
    explain: "A plain alert with nothing from your computer in it: just that a session needs you.",
    failed: "Couldn't turn alerts on. Try again.",
  },
  install: {
    title: "Install the app",
    lead: "It sits on your home screen, opens full screen and gets alerts.",
    button: "Install Miblo",
    ios: ["Tap Share in Safari's toolbar.", "Scroll and choose Add to Home Screen.", "Open Miblo from the new icon."],
    android: ["Tap the browser's ⋮ menu.", "Choose Install app or Add to Home screen.", "Open Miblo from the new icon."],
    other: "In the browser menu, choose Install app or Add to Home screen.",
    installed: "The app is already installed on this phone.",
    dismiss: "Not now",
  },
  pair: {
    title: "Connect this phone to your computer",
    lead: "See your AI sessions from anywhere. It takes a minute.",
    steps: ["On the computer, open the Miblo app.", "Tap Phone, then Show the QR code.", "Scan the QR code with this phone."],
    scan: "Scan the QR code",
    scanHint: "Point the camera at the QR code on the computer's screen.",
    noScanner: "Open the phone's camera and point it at the QR code: it opens the right link.",
    camera: "Couldn't use the camera. Scan with the phone's camera app instead.",
    stop: "Close the camera",
    cantScan: "Can't scan it?",
    pasteHelp: "Have the QR code's link (the terminal prints one, for example)? Paste it here.",
    paste: "QR code link",
    pasteButton: "Connect",
    invalid: "That link isn't a Miblo QR code.",
    paired: (name: string) => `Done! Phone connected to ${name}.`,
    privacy: "Everything arrives end-to-end encrypted: not even Miblo's server can read it.",
    noApp: "Haven't installed Miblo on the computer yet?",
    noAppLink: "See how",
    otherPhone: "Used Miblo on another phone before?",
    illustration: "The Miblo app on the computer, on the Phone screen, showing the QR code",
  },
  manageDevices: "See the account's phones and computers",
  remove: "Remove from this phone",
  removeConfirm: (name: string) => `Remove ${name} from this phone? You can connect it again later with the QR code.`,
  removed: (name: string) => `${name} removed.`,
  storageError: "This browser won't let the app keep the connection (private mode?).",
  close: "Close",
  computer: {
    details: "Details",
    approvalsOn: "Approve and reply: on",
    approvalsOff: "Approve and reply: not on for this phone",
    check: "Check code",
    checkHint: "The computer shows the same code in its list of phones.",
    current: "Showing now",
    show: "Show",
  },
  account: {
    menu: "Account and help",
    account: "My account",
    signIn: "Sign in",
    help: "Help",
    site: "Miblo website",
    title: "Account and help",
  },
  tech: {
    label: "For terminal users",
    on: "miblo phone on",
    link: "miblo account link",
    replies: "miblo plus replies on",
    channel: "claude --dangerously-load-development-channels server:miblo-phone",
    list: "miblo phone list",
  },
  plus: {
    name: "Miblo+",
    upsellTitle: "Reply and approve from your phone",
    upsellBody: "With Miblo+ you read the conversations, reply and approve your sessions' requests from anywhere.",
    upsellCta: "Discover Miblo+",
    url: "/en/plus",
    active: "Miblo+ is on for this computer",
    activeBody: "Conversations, replies and approvals from the phone are unlocked.",
    manage: "See my subscription",
    repair: "To approve and reply from this phone, connect it through your Miblo account.",
    open: "Open conversation",
    back: "Back",
    history: "Conversation",
    noHistory: "No messages yet. They show up here when the AI answers.",
    loading: "Fetching the messages from the computer…",
    historyBlocked: "The messages show up here once this phone is registered to approve and reply (see below).",
    historyOff: "The history is off on the computer. Confirm the settings in the Miblo app (or: miblo plus set history=on).",
    roles: { assistant: "AI", tool: "Tool", user: "You", phone: "You (phone)" },
    replyLabel: "Reply (beta)",
    replyPlaceholder: "Write to the session…",
    send: "Send",
    replyOnlyClaude: "For now, replying from the phone works only in Claude Code.",
    replyNeedsChannel: "This session doesn't take replies from the phone. Replying from the phone is still a test (beta) and only works in sessions started in a special way on the computer.",
    replyEmpty: "Write something before sending.",
    replyTooLong: "Message too long (up to 4000 characters).",
    replySent: "Sending to the computer…",
    replyHanded: "Sent to Claude Code, not delivered to the session yet.",
    replyStuck: "Not delivered yet. Replying from the phone is a test (beta): the session must have been started in a special way, or Claude Code drops the message.",
    replyDelivered: "Delivered to the session.",
    replyRefused: "The computer refused the message.",
    replyOffline: "No connection to the computer right now. Try again.",
    approvals: "Permission requests",
    approvalTitle: (tool: string) => `Wants to use ${tool}`,
    kindTitle: {
      command: "Wants to run a command",
      edit: "Wants to change a file",
      read: "Wants to read files",
      web: "Wants to go online",
      other: "Wants to use a tool",
    },
    approvalExpires: (s: number) => `expires in ${waitText(s)}`,
    approvalExpired: "Expired. Answer on the computer.",
    approvalPartial: "This request is too large to show in full here. From the phone you can only deny it; approve it on the computer.",
    approvalUnverified: "What arrived doesn't match the request. You can only deny it.",
    approve: "Approve",
    deny: "Deny",
    confirmApprove: "Confirm: approve exactly this",
    confirmDeny: "Confirm: deny",
    cancel: "Cancel",
    approvalSent: "Answer sent to the computer.",
    outcome: { allow: "Approved", deny: "Denied", timeout: "No answer in time: back to the computer", answered: "Answered on the computer" },
    untrusted: "Text from the AI: check it before acting on it.",
    descriptionByAi: "Description written by the AI (may not match the command)",
    command: "Command that will run",
    file: "File",
    diff: "Changes (− out, + in)",
    other: "Other fields",
    counts: (lines: number, chars: number) => `${lines} ${lines === 1 ? "line" : "lines"} · ${chars} characters`,
    multiline: "Multi-line command: read every line before approving.",
    long: "Long command: read it to the end before approving.",
    hidden: "Contains invisible or control characters, or stacked accent marks (shown as ⟨U+…⟩ or ⟨ESC⟩). For safety, the phone can only deny it.",
    nonAscii: "Contains non-ASCII characters, which can imitate ordinary letters. Check carefully.",
    readToEnd: "Scroll to the end of the request to enable Approve.",
    passkeyNeeded: "Approving asks for this phone's Face ID, fingerprint or PIN.",
    passkeyCancelled: "Approval cancelled: Face ID, fingerprint or PIN was not confirmed.",
    replyPasskey: "Sending asks for this phone's Face ID, fingerprint or PIN.",
    replyCancelled: "Message not sent: Face ID, fingerprint or PIN was not confirmed.",
    replyNoToken: "The computer has not opened replies for this conversation yet. Go back and open the conversation again.",
    rekeyed: "The computer changed this connection's key (a phone was removed). This phone already has the new one.",
    noPasskeys: "This phone has no Face ID, fingerprint or PIN available to the browser. Approving and replying are unavailable; you still see the sessions.",
    notEnrolled: "This computer hasn't accepted this phone yet. Check that it is linked to the same Miblo account (in the Miblo app on the computer: Sign in with your Miblo account).",
    revoked: "This phone was removed on the computer or in your account. To come back, connect this phone again through your account.",
    enrollTitle: "Approve and reply from this phone",
    enrollBody: "Tap below and confirm with the phone's Face ID, fingerprint or PIN. Every approval asks for it again, and the computer checks it.",
    enrollButton: "Turn on approvals",
    enrolling: "Registering with the computer…",
    enrollDone: (fp: string) => `Done! This phone can now approve and reply. Check code: ${fp}.`,
    enrollDoneTitle: "Done! This phone can now approve and reply.",
    checkCode: (fp: string) => `Check code: ${fp} (the computer shows the same one).`,
    enrollFailed: "The computer didn't accept it. The QR code lasts 10 minutes and works for one phone: make another in the Miblo app on the computer (Phone, Allow approvals on a phone) and scan it again.",
    enrollCancelled: "Not turned on: Face ID, fingerprint or PIN was not confirmed. Try again while the QR code is valid (10 minutes).",
    enrollExpired: "The QR code has expired. To turn this on, make another in the Miblo app on the computer (Phone, Allow approvals on a phone) and scan it again.",
    repliesOff: "Replying from the phone is off on this computer.",
    ok: "OK",
  },
  join: {
    title: "Sign in to your Miblo account",
    lead: "The phone connects through your Miblo account: sign in here and on the computer with the same account. No QR code.",
    legacy: "Sign in to your Miblo account to continue. The old QR code connections no longer work.",
    signIn: "Sign in",
    mfaSetup: "To connect a phone, your account needs a second step (Face ID, fingerprint or an authenticator app).",
    mfaSetupLink: "Turn on the second step",
    confirmTitle: "Confirm it's you",
    joinTitle: "Connect this phone to your account",
    joinBody: (email: string) => `This phone will join the account ${email}. Each computer linked to it shows this phone and accepts it only after you tap Allow there.`,
    joinPasskey: "We'll create a passkey for this phone (Face ID, fingerprint or PIN): it confirms every approval, reply and task.",
    joinNoPasskey: "This browser has no passkeys: the phone will only follow along (no approvals, replies or tasks).",
    joinButton: "Connect this phone",
    joining: "Connecting…",
    limit: "Your account already has 5 phones. Remove one in My account, Devices.",
    failed: "Couldn't connect right now. Try again.",
    cancelled: "Cancelled: Face ID, fingerprint or PIN wasn't confirmed.",
    waitingTitle: "Waiting for your computer",
    waitingBody: "On the computer, open the Miblo app and tap Sign in with your Miblo account. Then tap Allow when it shows this phone.",
    waitingTech: ["miblo account link", "miblo phone on"],
    allowTitle: "Type the computer's code",
    allowBody: "Waiting for confirmation on your computer: open the Miblo app, tap Allow and type the code below.",
    allowOn: (pc: string, min: number) => `${pc} · expires in ${min} min`,
    allowTech: ["miblo phone pending"],
    expiredOn: (pc: string) => `The request expired on ${pc} before it was confirmed.`,
    askAgain: "Ask again",
    askedAgain: "Request sent: confirm it on your computer.",
    deniedOn: (pc: string) => `${pc} turned this phone away. If that was a mistake, remove this phone in My account and connect it again.`,
    checkNow: "Check now",
    detail: {
      bad_key: (pc: string) => `Details: ${pc} sent the access, but it does not open with this phone's key (it was made for another attempt). On the computer, under Phone, revoke this phone and connect again.`,
      bad_sig: (pc: string) => `Details: the access ${pc} sent is not signed by it. Tap Check now; if it stays, revoke this phone on the computer and connect again.`,
      not_pinned: (pc: string) => `Details: the access from ${pc} opens, but this phone did not keep the confirmation of the code you typed (another attempt, or the session was remade). On the computer, under Phone, revoke this phone and connect again.`,
      type_code: (pc: string) => `Details: ${pc} is showing the code. Type it above.`,
      code_sent: (pc: string) => `Details: code sent; ${pc} is checking it.`,
      held: (pc: string) => `Details: ${pc} accepted the code and waits for a confirmation on a phone it already has. If none can answer, revoke it on the computer: this phone then joins with the code alone.`,
      allow: (pc: string) => `Details: ${pc} saw this phone and has not shown the code yet. On the computer, open Phone.`,
      no_answer: "Details: no computer answered yet. Check that Miblo is on at the computer (Miblo app, Phone tab, or `miblo phone status`).",
    },
    joined: (name: string) => `Done! ${name} accepted this phone.`,
    signedInAs: (email: string) => `Account: ${email}`,
  },
  code: {
    title: (pc: string) => `New computer: ${pc}`,
    help: (pc: string) => `Type the 6-digit code ${pc} shows (in the Miblo app or the terminal). Only type it if you are looking at that computer now.`,
    label: "Computer's code",
    submit: "Confirm with the passkey",
    submitNoPasskey: "Confirm",
    sending: "Confirming…",
    sent: "Sent: the computer checks the code.",
    wrong: (left: number) => `Wrong code. ${left === 1 ? "1 try left" : `${left} tries left`}.`,
    invalid: "Type the 6 digits the computer shows.",
    cancelled: "Cancelled: the passkey was not confirmed.",
    failed: "Could not send it now. Try again.",
    gone: "That request changed on the computer: look at the code again.",
    held: (pc: string) => `Right code. Now confirm on a phone you already use with ${pc}: it asks for the code the computer shows.`,
    reuseTitle: "You already have a Miblo passkey on this phone. Use the same one?",
    reuseYes: "Use the one I have (recommended)",
    reuseNo: "Create another",
    repairing: "Asking the computer…",
    repairFailed: "Could not ask again. Try again.",
    retry: "Try again",
  },
  confirm: {
    title: (pc: string) => `${pc} wants to turn on:`,
    admitTitle: (pc: string) => `${pc}: a new phone wants access`,
    admitBody: (name: string, about: string) => `${name}${about ? ` (${about})` : ""}. Only allow it if it is yours.`,
    on: { approvals: "approvals from the phone", replies: "replies from the phone", history: "the history on the phone", permissive: "replies also into sessions that do not ask for permissions", tasks: "new tasks from the phone" } as Record<string, string>,
    timeout: (s: number) => `waiting ${waitText(s)} for the phone on an approval`,
    taskMax: (m: number) => `tasks of up to ${m} min`,
    folder: (path: string) => `tasks in the folder ${path}`,
    help: "Type the 6-digit code the computer shows now and confirm with the passkey.",
    expires: (s: number) => `Expires in ${s} s`,
    approve: "Approve on the phone",
    deny: "Deny",
    done: { applied: "Turned on at the computer.", cancelled: "Cancelled.", expired: "Expired.", wrong_code: "Wrong code 3 times: cancelled.", failed: "The computer could not apply it." } as Record<string, string>,
    phoneOnly: "Confirm on a phone: this request can only be approved on a phone.",
  },
  trust: {
    codeTitle: (pc: string) => `Code for ${pc}`,
    codeHelp: "This computer runs a Miblo older than 1.23: there, tap Allow in the Miblo app and type this code (or run miblo phone approve with --code). Never type it anywhere else.",
    fp: (fp: string) => `Computer key: ${fp}`,
    preparing: "Preparing the code…",
    mismatch: "A computer was given another key for this phone: the code will not match. Do not allow it; remove this phone in My account and connect it again.",
    newTitle: (pc: string) => `New computer: ${pc}`,
    newBody: (code: string) => `It says you allowed this phone with the code ${code}. Was that you, on your computer?`,
    confirm: "Yes, it was me",
    reject: "I don't recognise it",
    rejected: "Turned down: this computer gets nothing from this phone.",
    confirmed: (pc: string) => `${pc} confirmed.`,
    tooMany: "Too many pairing attempts: someone may be trying to get in. No new code is shown for an hour. If it wasn't you, change your account's password and second step.",
  },
  chat: {
    jump: "Go to the end",
    jumpNew: (n: number) => (n === 1 ? "1 new message" : `${n} new messages`),
    working: "Working…",
    copy: "Copy",
    copied: "Copied",
    more: "Show all",
    less: "Show less",
    image: (alt: string) => (alt ? `[image: ${alt}]` : "[image]"),
    openLink: (url: string) => `Open this address?\n\n${url}`,
    today: "Today",
    yesterday: "Yesterday",
    edited: (path: string) => `Edited ${path}`,
    wrote: (path: string) => `Created ${path}`,
    ran: (cmd: string) => `Ran: ${cmd}`,
    read: (path: string) => `Read ${path}`,
    readN: (n: number) => `Read ${n} files`,
    searched: (q: string) => `Searched: ${q}`,
    searchedN: (n: number) => `Ran ${n} searches`,
    web: (q: string) => `On the web: ${q}`,
    agent: (q: string) => `Agent: ${q}`,
    todo: "Updated the task list",
    used: (name: string) => `Used ${name}`,
    usedN: (n: number) => `Used ${n} tools`,
    failed: "failed",
    output: "Output",
    changes: "Changes",
    disabledHow: "How to turn it on",
    noReply: "Replying from here isn't available for this session.",
    offPlaceholder: "Replies are off here",
    replyOff: "To reply from here, turn replies on at the computer.",
    replyChannel: "To reply from here, start the session on the computer with Miblo's channel (beta).",
    replyOther: "Replying from here works in Claude Code only. For other AIs, use New task.",
    replyTask: "A task from the phone: to ask for more, create a new task.",
    noPasskey: "This phone has no passkey: you can follow along, not reply.",
    notLinked: "This computer hasn't accepted this phone yet.",
    revoked: "This phone was removed on this computer.",
    offline: "No connection to the computer right now.",
  },
  task: {
    newTask: "New task",
    title: "New task on the computer",
    lead: "Ask an AI to work on the computer, in a folder you allowed there. You follow everything here.",
    tool: "AI",
    folder: "Folder",
    prompt: "What to do",
    placeholder: "E.g. run the tests and fix what fails",
    willRun: (tool: string, path: string) => `Will run ${tool} in ${path}`,
    limit: (min: number) => `Stops by itself after ${min} min. Permission requests come here under Approvals.`,
    send: "Send task",
    passkey: "Sending asks for this phone's Face ID, fingerprint or PIN.",
    off: "Tasks from the phone are off on this computer.",
    offHow: "On the computer, choose a folder and turn tasks on (it asks for your Miblo's code):",
    offTech: ["miblo plus tasks folder add <folder>", "miblo plus tasks on"],
    noTools: "No supported AI found on the computer (Claude Code, Codex, Gemini CLI or Copilot).",
    noFolders: "No folder allowed on the computer yet.",
    loading: "Asking the computer what can run…",
    sending: "Sending…",
    started: "Task started on the computer.",
    refused: (why: string) => `The computer refused the task (${why}).`,
    cancelled: "Not sent: Face ID, fingerprint or PIN wasn't confirmed.",
    offline: "No connection to the computer right now. Try again.",
    empty: "Write what the AI should do.",
    tooLong: "Text too long (up to 4000 characters).",
    noToken: "The computer hasn't allowed tasks for this phone yet. Close and open again.",
    stop: "Stop",
    stopConfirm: "Stop this task now?",
    stopping: "Stopping…",
    recent: "Recent tasks",
    states: { running: "Running", done: "Done", failed: "Failed", stopped: "Stopped" },
    reasons: {
      busy: "a task is already running",
      rate_limited: "hourly task limit",
      off: "tasks are off",
      unknown_folder: "folder not allowed",
      folder_changed: "the folder changed on the computer",
      unknown_tool: "AI not found",
      passkey_none: "this phone has no passkey",
      time_limit: "time limit",
      output_limit: "too much output",
      phone: "stopped from the phone",
      computer: "stopped on the computer",
    },
    needsPlus: "New task is part of Miblo+.",
  },
  vault: {
    title: "Keep in your account",
    lead: "Keep the computers connected to this phone in your Miblo account. On a new phone, just sign in and get them back. It's encrypted: not even Miblo can read it.",
    restoreLead: "Sign in to your account to get back the computers you kept.",
    nothingKept: "No computer kept in your account yet. Connect this phone with the QR code; then you can keep it from Settings.",
    signIn: "Sign in",
    setup: "To keep them, your account needs to sign in with Face ID or fingerprint (a passkey).",
    setupLink: "Turn it on in my account",
    create: "Keep in my account",
    open: "See kept computers",
    working: "Confirming…",
    noPrf: "This phone or browser can't open what is kept. The computers stay connected on this phone.",
    noPasskey: "To open it, use the account's Face ID or fingerprint (the authenticator app's code doesn't work here).",
    cancelled: "Face ID, fingerprint or PIN was not confirmed.",
    failed: "Couldn't open it. Try again.",
    otherKey: "This passkey doesn't open what is kept yet. Open it with the one that kept it, then allow this one.",
    empty: "Nothing kept yet. This phone's next computers go in here.",
    here: "on this phone",
    restore: "Use on this phone",
    forget: "Remove from account",
    save: "Keep",
    seen: (when: string) => `seen ${when}`,
    neverSeen: "not seen yet",
    notInVault: (n: number) => (n === 1 ? "1 computer on this phone isn't kept: to keep it, scan its QR code again." : `${n} computers on this phone aren't kept: to keep them, scan their QR codes again.`),
    restored: "Restored to see the sessions. To approve and reply, register this phone again in the Miblo app on the computer (Phone, Allow approvals on a phone).",
    addKey: "Allow another passkey",
    unlocked: "Done: these are the computers kept in your account.",
    saveFailed: "Couldn't keep it: the change was not saved. Try again.",
    rekeyed: "A passkey left your account: what is kept got a new key, which only this one opens. Allow the others again.",
    rollback: "What arrived is older than what this phone already saw. For safety, it was not opened.",
  },
};

export function phoneStrings(lang: Locale): PhoneStrings {
  return lang === "en" ? en : pt;
}
