// Copy of the account's security pages: the second-factor step after signing in, and the account's
// Security section (how you sign in, emergency codes, where the account is open). The miblo.ai
// copy, with what a self-hosted server signs in with (a password, not an email) and without the
// saved-Miblos vault it does not have.
// Plain words first: "passkey" only as the name people will also see in their phone's prompts.
import type { Locale } from "@/lib/i18n";

const pt = {
  verifyTitle: "Confirme que é você",
  verifyLead: "Sua conta é protegida. Confirme com a digital, o rosto ou o código do app autenticador.",
  usePasskey: "Confirmar com digital ou rosto",
  useTotp: "Usar o código do app autenticador",
  useRecovery: "Usar um código de emergência",
  code: "Código de 6 dígitos",
  recoveryCode: "Código de emergência",
  confirm: "Confirmar",
  checking: "Conferindo…",
  back: "Voltar",
  badCode: "Código incorreto ou já usado. Tente o próximo código do app.",
  locked: "Muitas tentativas erradas. A confirmação desta conta está bloqueada por 15 minutos.",
  cancelled: "Não foi confirmado. Tente de novo quando quiser.",
  failed: "Não deu para confirmar. Tente de novo.",
  recoveryNote: "Um código de emergência devolve o acesso à conta.",
  freshNeeded: "Por segurança, confirme que é você para fazer isto.",
  reconfirmTitle: "Confirme que é você pelo e-mail",
  reconfirmBody: "Você entrou aprovando pelo e-mail em outro aparelho. Para mudar a segurança da conta, mandamos um código para o seu e-mail.",
  reconfirmSend: "Mandar o código",
  reconfirmCode: "Código do e-mail",
  reconfirmDone: "Confirmado. Pode continuar.",
  setupNeeded: "Proteja sua conta com a digital, o rosto ou um app autenticador para usar isto.",
  title: "Segurança",
  lead: "Como você entra na conta e onde ela está aberta.",
  // Status at the top
  statusOk: "Sua conta está protegida",
  statusOkBody: "Além da senha, entrar pede a sua digital, o rosto ou o app autenticador.",
  statusWeak: "Proteja sua conta em 1 minuto",
  statusWeakBody: "Sem um segundo fator nada funciona neste servidor. Use a digital ou o rosto deste aparelho: fica mais seguro e você entra com um toque.",
  recommended: "Recomendado",
  protectNow: "Usar digital ou rosto",
  protectBusy: "Esperando o aparelho…",
  // Emergency codes offered right after the first passkey
  nextCodesTitle: "Último passo: códigos de emergência",
  nextCodesBody: "Se você perder este aparelho, um destes códigos deixa você entrar. Guarde num lugar seguro (gerenciador de senhas ou papel).",
  nextCodesButton: "Criar meus códigos",
  codesCopy: "Copiar os códigos",
  codesCopied: "Copiados!",
  codesDownload: "Baixar arquivo",
  codesDone: "Já guardei",
  codesFile: "codigos-de-emergencia-miblo.txt",
  // Passkeys
  passkeys: "Entrar com digital ou rosto",
  passkeysHint: "Cada aparelho onde você usa a digital, o rosto ou o PIN para entrar (as chamadas passkeys).",
  noPasskeys: "Nenhum aparelho ainda.",
  addPasskey: "Adicionar este aparelho",
  addAnother: "Adicionar outro aparelho",
  passkeyName: "Nome deste aparelho",
  passkeyDefault: "Meu aparelho",
  passkeyAdded: "Pronto! Este aparelho já entra com digital ou rosto.",
  passkeyNew: "Novo",
  passkeyCreated: (d: string) => `adicionado em ${d}`,
  prfYes: "abre os Miblos salvos",
  prfNo: "não abre os Miblos salvos",
  remove: "Remover",
  removeConfirm: (name: string) => `Remover “${name}”? Ele deixa de entrar na conta.`,
  removed: "Removido.",
  removeLast: "Esta é a última forma de confirmar a conta deste servidor: adicione outra antes de remover.",
  totp: "App autenticador",
  totpHint: "Para quem prefere um código de 6 dígitos de um app como Google Authenticator, 1Password ou Aegis.",
  totpOn: "Ativado.",
  totpSetup: "Configurar o app autenticador",
  totpScan: "Escaneie com o app autenticador (ou digite a chave). Ela aparece só agora.",
  totpKey: "Chave",
  totpConfirm: "Digite o primeiro código do app para ativar",
  totpDone: "App autenticador ativado.",
  totpUnavailable: "O app autenticador não está disponível agora. Use a digital ou o rosto.",
  recovery: "Códigos de emergência",
  recoveryHint: "Códigos de uso único para entrar se você perder os seus aparelhos.",
  recoveryLeft: (n: number) => (n === 1 ? "Resta 1 código." : `Restam ${n} códigos.`),
  recoveryNone: "Nenhum código criado.",
  recoveryGenerate: "Criar códigos novos",
  recoveryShown: "Guarde estes códigos num lugar seguro. Eles aparecem só agora, e os antigos pararam de valer:",
  sessions: "Onde sua conta está aberta",
  sessionsHint: "Navegadores e aparelhos que entraram na sua conta. Não reconhece algum? Toque em Sair dele.",
  thisOne: "Este aparelho",
  verified: "confirmado",
  notVerified: "só com a senha",
  lastSeen: (d: string) => `usado em ${d}`,
  unknownDevice: "Aparelho desconhecido",
  revoke: "Sair dele",
  revokeOthers: "Sair de todos os outros",
  revoked: "Pronto, esse acesso foi encerrado.",
  revokedOthers: "Pronto, só este aparelho continua dentro.",
  more: "Mais opções",
  moreHint: "App autenticador e códigos de emergência.",
  vault: "Miblos salvos para o celular",
  vaultHint: "Os Miblos que o app do celular guardou na conta, trancados com a sua digital ou rosto. Nem nós conseguimos ver.",
  vaultOn: "Você tem Miblos salvos. Eles se gerenciam pelo app do celular (miblo.ai/app).",
  vaultOff: "Nada salvo. Isso se faz pelo app do celular (miblo.ai/app).",
  vaultDelete: "Apagar os Miblos salvos",
  vaultDeleteConfirm: "Apagar os Miblos salvos na conta? Eles continuam nos celulares, mas não ficam mais guardados na conta.",
  saved: "Pronto.",
  error: "Algo deu errado. Tente de novo.",
  noWebauthn: "Este navegador não cria passkeys. Use um app autenticador (em Mais opções).",
};

export type SecurityCopy = typeof pt;

const en: SecurityCopy = {
  verifyTitle: "Confirm it's you",
  verifyLead: "Your account is protected. Confirm with your fingerprint, face or authenticator app's code.",
  usePasskey: "Confirm with fingerprint or face",
  useTotp: "Use the authenticator app's code",
  useRecovery: "Use an emergency code",
  code: "6-digit code",
  recoveryCode: "Emergency code",
  confirm: "Confirm",
  checking: "Checking…",
  back: "Back",
  badCode: "Wrong or already used code. Try the app's next code.",
  locked: "Too many wrong attempts. This account's confirmation is locked for 15 minutes.",
  cancelled: "It wasn't confirmed. Try again whenever you like.",
  failed: "Couldn't confirm. Try again.",
  recoveryNote: "An emergency code gives you back the account.",
  freshNeeded: "For safety, confirm it's you to do this.",
  reconfirmTitle: "Confirm it's you by email",
  reconfirmBody: "You signed in by approving from the email on another device. To change the account's security, we send a code to your email.",
  reconfirmSend: "Send the code",
  reconfirmCode: "Code from the email",
  reconfirmDone: "Confirmed. You can go on.",
  setupNeeded: "Protect your account with your fingerprint, face or an authenticator app to use this.",
  title: "Security",
  lead: "How you sign in to the account and where it's open.",
  statusOk: "Your account is protected",
  statusOkBody: "Besides the password, signing in asks for your fingerprint, face or authenticator app.",
  statusWeak: "Protect your account in a minute",
  statusWeakBody: "Nothing works on this server without a second factor. Use this device's fingerprint or face: it's safer and you sign in with one tap.",
  recommended: "Recommended",
  protectNow: "Use fingerprint or face",
  protectBusy: "Waiting for the device…",
  nextCodesTitle: "Last step: emergency codes",
  nextCodesBody: "If you lose this device, one of these codes lets you in. Keep them somewhere safe (a password manager or paper).",
  nextCodesButton: "Create my codes",
  codesCopy: "Copy the codes",
  codesCopied: "Copied!",
  codesDownload: "Download file",
  codesDone: "I've kept them",
  codesFile: "miblo-emergency-codes.txt",
  passkeys: "Sign in with fingerprint or face",
  passkeysHint: "Each device where you use your fingerprint, face or PIN to sign in (called passkeys).",
  noPasskeys: "No devices yet.",
  addPasskey: "Add this device",
  addAnother: "Add another device",
  passkeyName: "Name of this device",
  passkeyDefault: "My device",
  passkeyAdded: "Done! This device now signs in with fingerprint or face.",
  passkeyNew: "New",
  passkeyCreated: (d: string) => `added on ${d}`,
  prfYes: "opens the saved Miblos",
  prfNo: "doesn't open the saved Miblos",
  remove: "Remove",
  removeConfirm: (name: string) => `Remove “${name}”? It will no longer sign in to the account.`,
  removed: "Removed.",
  removeLast: "This is the last way to confirm this server's account: add another one before removing it.",
  totp: "Authenticator app",
  totpHint: "For those who prefer a 6-digit code from an app such as Google Authenticator, 1Password or Aegis.",
  totpOn: "On.",
  totpSetup: "Set up the authenticator app",
  totpScan: "Scan it with the authenticator app (or type the key). It shows only now.",
  totpKey: "Key",
  totpConfirm: "Type the app's first code to turn it on",
  totpDone: "Authenticator app turned on.",
  totpUnavailable: "The authenticator app isn't available right now. Use your fingerprint or face.",
  recovery: "Emergency codes",
  recoveryHint: "Single-use codes to sign in if you lose your devices.",
  recoveryLeft: (n: number) => (n === 1 ? "1 code left." : `${n} codes left.`),
  recoveryNone: "No codes created.",
  recoveryGenerate: "Create new codes",
  recoveryShown: "Keep these codes somewhere safe. They show only now, and the old ones stopped working:",
  sessions: "Where your account is open",
  sessionsHint: "Browsers and devices signed in to your account. Don't recognise one? Tap Sign it out.",
  thisOne: "This device",
  verified: "confirmed",
  notVerified: "password only",
  lastSeen: (d: string) => `used on ${d}`,
  unknownDevice: "Unknown device",
  revoke: "Sign it out",
  revokeOthers: "Sign out all the others",
  revoked: "Done, that sign-in was ended.",
  revokedOthers: "Done, only this device stays signed in.",
  more: "More options",
  moreHint: "Authenticator app and emergency codes.",
  vault: "Miblos saved for your phone",
  vaultHint: "The Miblos the phone app kept in the account, locked with your fingerprint or face. Not even we can see them.",
  vaultOn: "You have saved Miblos. They're managed from the phone app (miblo.ai/app).",
  vaultOff: "Nothing saved. That's done from the phone app (miblo.ai/app).",
  vaultDelete: "Delete the saved Miblos",
  vaultDeleteConfirm: "Delete the Miblos saved in the account? They stay on the phones, but are no longer kept in the account.",
  saved: "Done.",
  error: "Something went wrong. Try again.",
  noWebauthn: "This browser can't create passkeys. Use an authenticator app (under More options).",
};

export function securityCopy(lang: Locale): SecurityCopy {
  return lang === "en" ? en : pt;
}
